### ISSUE TITLE
Official repository

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-archive#1]
Given Bitbucket is closing down Mercurial hosting, we're (I'm one of the Pygments maintainers) are looking at migrating to GitHub. Could we take over this organization/repository please, for easy discoverability? We'd also remove the "unofficial" tag :)

**Comment by zengxs** [comment]
I'm very happy to hear that Pygment will be migrating to GitHub, I have invited you to join this organization. And any other things that need to be help, please tell me.

**Comment by Anteru** [comment]
Thanks! Well, happy -- Bitbucket is removing support for Mecurial, which was one of the main reasons we used it ...

Anyways :) There are only two more things -- we'd like to become owners/administrators of the organization, so we can add/remove people as needed. And please add @birkenfeld as well (he's the main author of pygments.)

**Comment by birkenfeld** [comment]
I'm in, thanks for the quick turnaround! Now we "only" have to work out issue migration... :)

**Comment by Anteru** [comment]
Indeed, thanks for fixing this quickly! I've imported the Pygments repository here: https://github.com/Anteru/pygments-main, which I think has yielded one branch per open PR. I'll look at the issues next.
